{
 "title": "Trivy Project Security Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project Name",
    "query": "SELECT DISTINCT project FROM build_reports ORDER BY project;"
   }
  ]
 },
 "panels": [
  { "title": "Latest Build Summary", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Build Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN EXISTS (SELECT 1 FROM trivy_results tr JOIN build_reports br ON tr.build_id = br.id WHERE br.project = '$project' AND tr.severity IN ('HIGH','CRITICAL')) THEN 0 ELSE 1 END as status;"
    }
   ]
  },
  {
   "title": "🔴 Secrets Exposed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS secret_count\nFROM trivy_secrets ts\nJOIN build_reports br ON ts.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = '$project'\n  );\n"
    }
   ]
  },
  {
   "title": "🔴 Critical Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = '$project'\n  )\n  AND tr.severity = 'CRITICAL' and tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟠 High Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS count\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n    SELECT MAX(timestamp) \n    FROM build_reports \n    WHERE project = br.project\n  )\n  AND tr.severity = 'HIGH' and tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟡 Medium Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS count\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n    SELECT MAX(timestamp) \n    FROM build_reports \n    WHERE project = br.project\n  )\n  AND tr.severity = 'MEDIUM' and tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟢 Low Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS count\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n    SELECT MAX(timestamp) \n    FROM build_reports \n    WHERE project = br.project\n  )\n  AND tr.severity = 'LOW' and tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "✅ Approved Exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS count\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n    SELECT MAX(timestamp) \n    FROM build_reports \n    WHERE project = br.project\n  )\n  AND tr.is_exception=1;\n"
    }
   ]
  },
  {
   "title": "Latest Build Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT br.tag\nFROM build_reports br\nWHERE br.project = '$project'\nORDER BY br.timestamp DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Summary of Last Build",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    br.id AS build_id,\n    br.image,\n    br.tag,\n    br.ci_url,\n    br.timestamp,\n\n    -- Count vulnerabilities by severity\n    COUNT(*) FILTER (WHERE tr.severity = 'CRITICAL' AND tr.is_exception=0) AS critical_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'HIGH' AND tr.is_exception=0)     AS high_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'MEDIUM' AND tr.is_exception=0)   AS medium_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'LOW' AND tr.is_exception=0)      AS low_count,\n    COUNT(*) FILTER (WHERE tr.severity IS NULL OR tr.severity = '' AND tr.is_exception=0) AS unknown_count,\n    COUNT(*) FILTER (WHERE tr.is_exception=1)  AS exception_count,\n\n    -- Total vulnerabilities and secrets\n    COUNT(DISTINCT tr.id) AS total_vulnerabilities,\n    COUNT(DISTINCT ts.id) AS total_secrets\n\nFROM build_reports br\nLEFT JOIN trivy_results tr ON tr.build_id = br.id\nLEFT JOIN trivy_secrets ts ON ts.build_id = br.id\n\nWHERE br.project = '$project'\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = br.project\n  )\n\nGROUP BY br.id, br.project, br.image, br.tag, br.ci_url, br.timestamp\nORDER BY br.timestamp DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Secrets Exposed on the latest build",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    ts.target AS file_name,\n    ts.rule_id,\n    ts.category,\n    ts.severity,\n    ts.title,\n    ts.match,\n    ts.timestamp\nFROM trivy_secrets ts\nJOIN build_reports br ON ts.build_id = br.id\nWHERE br.project = '$project'\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = '$project'\n  )\nORDER BY ts.timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Vulnerabilities of the latest build",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    tr.vuln_id,\n    tr.pkg_name,\n    tr.installed,\n    tr.fixed,\n    tr.severity,\n    tr.status,\n    tr.primary_url,\n    tr.timestamp\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project' AND tr.is_exception=0\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = '$project'\n  )\nORDER BY tr.severity DESC, tr.vuln_id;\n"
    }
   ]
  },
  {
   "title": "⚠️ Ignored Vulnerabilities (Approved Exceptions)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    tr.vuln_id,\n    tr.pkg_name,\n    tr.installed,\n    tr.fixed,\n    tr.severity,\n    tr.status,\n    tr.primary_url,\n    tr.timestamp\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project' AND tr.is_exception=1\n  AND br.timestamp = (\n      SELECT MAX(timestamp) \n      FROM build_reports \n      WHERE project = '$project'\n  )\nORDER BY tr.severity DESC, tr.vuln_id;\n"
    }
   ]
  },
  { "title": "Overall Project Summary", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Build Vs Vurnerbilites",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    br.id AS build_id,\n    tr.severity AS metric,\n    COUNT(*) AS value\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\nGROUP BY br.id, tr.severity\n\nUNION ALL\n\nSELECT \n    br.id AS build_id,\n    'CRITICAL' AS metric,   -- Secrets forced into CRITICAL bucket\n    COUNT(*) AS value\nFROM trivy_secrets ts\nJOIN build_reports br ON ts.build_id = br.id\nWHERE br.project = '$project'\n  AND ts.severity = 'CRITICAL'\nGROUP BY br.id\n\nORDER BY build_id;\n"
    }
   ]
  },
  {
   "title": "Secrets by Category",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT ts.category as metric, COUNT(*) as value FROM trivy_secrets ts JOIN build_reports br ON ts.build_id = br.id WHERE br.project = '$project' GROUP BY ts.category;"
    }
   ]
  },
  {
   "title": "Build History",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT \n    br.id,\n    br.image,\n    br.tag,\n    br.timestamp,\n    CASE \n        WHEN EXISTS (\n            SELECT 1 \n            FROM trivy_results tr \n            WHERE tr.build_id = br.id \n              AND tr.severity IN ('HIGH','CRITICAL')\n        ) \n        THEN 'FAIL' \n        ELSE 'PASS' \n    END AS build_status,\n    'Build Details' AS reference_text,  -- Show this in the table\n    br.id AS reference_id               -- Use this for linking\nFROM build_reports br\nWHERE br.project = '$project'\nORDER BY br.timestamp DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "Top Vulnerabilities (by vuln_id)",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 64 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT tr.vuln_id,\n       COUNT(*) AS occurrences,\n       MIN(tr.severity) AS severity\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.project = '$project'\nGROUP BY tr.vuln_id\nORDER BY occurrences DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "Recent Secrets Detected",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT ts.rule_id, ts.category, ts.severity, ts.title, ts.match, ts.timestamp FROM trivy_secrets ts JOIN build_reports br ON ts.build_id = br.id WHERE br.project = '$project' ORDER BY ts.timestamp DESC LIMIT 20;"
    }
   ]
  }
 ]
}